apiVersion: v1
kind: ConfigMap
metadata:
  name: java-app-config
  namespace: java-app
data:
  application.yaml: |
    spring:
      application:
        name: app
      datasource:
        username: root
        password: password
        url: jdbc:mysql://mysql:3306/challenge
        driver-class-name: com.mysql.cj.jdbc.Driver
      flyway:
        url: jdbc:mysql://mysql:3306/challenge
        user: root
        password: password
        enabled: true
    management:
      endpoints:
        web:
          exposure:
            include: ${ACTUATOR_ENDPOINTS:health,info,prometheus}
