apiVersion: v1
kind: ConfigMap
metadata:
  name: java-app-config
  namespace: java-app
data:
  application.yaml: |
    spring:
      application:
        name: app
      datasource:
        username: root
        password: jfo5XMSE20
        url: jdbc:mysql://mysql:3306/my_database
        driver-class-name: com.mysql.cj.jdbc.Driver
      flyway:
        url: jdbc:mysql://mysql:3306/my_database
        user: root
        password: jfo5XMSE20
        enabled: true
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus
